version: '3'

services:
  web:
    image: henaras/simpleweb:1
    ports:
      - "8000:8000"
    deploy:
     resources:
        limits:
          cpus: '0.25'
          memory: 256M
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
     resources:  
        limits:
          cpus: '0.25'
          memory: 256M

  visualizer:
    image: henaras/visualizer
    ports:
      - "5000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  auto-scaler:
    image: mrboisvert/auto-scaler
    ports:
      - "7000:7000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  auto-scaler-plots:
    image: mrboisvert/auto-scaler-plots
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.role == manager]